### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by g48r137** [WaPoNe/module-input-fields-validator#1]
In composer.json we have
"require": {
        "php": "^7||^8"...

but  inside module-input-fields-validator/Plugin/AbstractInputFieldsValidator.php
readonly is used in constructor.

readonly was introduced in PHP 8.1

I sugest to remove readonly to make it compatible with PHP 7.

**Comment by WaPoNe** [comment]
@g48r137 you're right!

Thanks for your contribution.

I've released [1.1.1](https://github.com/WaPoNe/module-input-fields-validator/releases/tag/1.1.1) version.

**Comment by g48r137** [comment]
Thank you!

module-input-fields-validator/Utility/Configurations.php you use mixed type, like this:
public function getRegEx(): mixed

But it was introduced in PHP 8.

Version	Description
8.3.0	Support for class, interface, trait, and enum constant typing has been added.
8.2.0	Support for DNF types has been added.
8.2.0	Support for the literal type true has been added.
8.2.0	The types null and false can now be used standalone.
8.1.0	Support for intersection types has been added.
8.1.0	Returning by reference from a void function is now deprecated.
8.1.0	Support for the return only type never has been added.
8.0.0	Support for mixed has been added.
8.0.0	Support for the return only type static has been added.
8.0.0	Support for union types has been added.
7.4.0	Support for class properties typing has been added.
7.2.0	Support for object has been added.
7.1.0	Support for iterable has been added.
7.1.0	Support for void has been added.
7.1.0	Support for nullable types has been added.



"Fatal Error: 'Uncaught TypeError: Return value of WaPoNe\\InputFieldsValidator\\Utility\\Configurations::getRegEx() must be an instance of WaPoNe\\InputFieldsValidator\\Utility\\mixed, string returned in \/var\/www\/html\/vendor\/wapone\/module-input-fields-validator\/Utility\/Configurations.php:44\nStack trace:\n#0 \/var\/www\/html\/vendor\/wapone\/module-input-fields-validator\/Plugin\/AbstractInputFieldsValidator.php(60): WaPoNe\\InputFieldsValidator\\Utility\\Configurations->getRegEx()\n#1 \/var\/www\/html\/vendor\/wapone\/module-input-fields-validator\/Plugin\/OrderSourceLogger.php(38): WaPoNe\\InputFieldsValidator\\Plugin\\AbstractInputFieldsValidator->validateInput('test', 'First Name', 'wapone_ifv\/conf...')\n#2 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): WaPoNe\\InputFieldsValidator\\Plugin\\OrderSourceLogger->beforeSave(Object(Magento\\Sales\\Model\\OrderRepository\\Interceptor), Object(Magento\\Sales\\Model\\Order\\Interceptor))\n#3 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Sales\\Model\\OrderRepo' in '\/var\/www\/html\/vendor\/wapone\/module-input-fields-validator\/Utility\/Configurations.php' on line 44"

**Comment by WaPoNe** [comment]
Thanks again.

I was (I am) tempted to avoid to support PHP 7 :-)

I've released [1.1.2](https://github.com/WaPoNe/module-input-fields-validator/releases/tag/1.1.2) version.
