### ISSUE TITLE
Validate State/Region field

### ISSUE THREAD

**Issue by bafmaamy** [WaPoNe/module-input-fields-validator#3]
Hi,
Some people reporting failing of create an order with genue name in State/Region. Maybe the validation method for that field is not the right way to be done, because it conflicts with payment modules or something else I think. I just removed it for now.
Cheers

**Comment by WaPoNe** [comment]
Hi @bafmaamy,
thanks for your contribution.
For now I've added a configuration field to set 'Region fields validation'.

I've released it in the [1.2.0](https://github.com/WaPoNe/module-input-fields-validator/releases/tag/1.2.0) version.
